# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
