# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0002_weight_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='Gym',
            field=models.BooleanField(default=False),
        ),
    ]
