# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0003_weight_gym'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='Gym',
            new_name='gym',
        ),
        migrations.AddField(
            model_name='weight',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
