# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website1', '0004_auto_20170828_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='date',
            new_name='timestamp',
        ),
    ]
